<?xml version="1.0" encoding="utf-8"?><Database Name="PetShopDoBairro" Class="BancoDeDadosPadraoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\;Initial Catalog=PetShopDoBairro;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PetShopDoBairroConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EMPRESA" Member="EMPRESA">
    <Type Name="EMPRESA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMEFANTASIA" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="RAZAOSOCIAL" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CNPJ" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ENDERECO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="BAIRRO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CIDADE" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TELEFONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TELEFONE2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="EMPRESA_FILIAL" Member="FILIAL" ThisKey="ID" OtherKey="IDEMPRESA" Type="FILIAL" />
    </Type>
  </Table>
  <Table Name="dbo.USUARIO" Member="USUARIO">
    <Type Name="USUARIO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CPFCNPJ" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TIPOPESSOA" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="SENHA" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RAZAOSOCIAL" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="INSCRICAOESTADUAL" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="INSCRICAOMUNICIPAL" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ENDERECO" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="BAIRRO" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CIDADE" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TELCELLWHAT" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="RECEBERINFORWHATSAPP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RECEBERINFOREMAIL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CONHECEUATRAVES" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="USUARIO_EQUIPAMENTO" Member="EQUIPAMENTO" ThisKey="ID" OtherKey="IDUSUARIO" Type="EQUIPAMENTO" />
    </Type>
  </Table>
  <Table Name="dbo.EQUIPAMENTO" Member="EQUIPAMENTO">
    <Type Name="EQUIPAMENTO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NUMEROSERIE" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="NUMEROTOMABAMENTO" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MARCA" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MODELO" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDUSUARIO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="EQUIPAMENTO_MANUTENCAOEQUIPAMENTO" Member="MANUTENCAOEQUIPAMENTO" ThisKey="ID" OtherKey="IDEQUIPAMENTO" Type="MANUTENCAOEQUIPAMENTO" />
      <Association Name="EQUIPAMENTO_ORDEMSERVICO" Member="ORDEMSERVICO" ThisKey="ID" OtherKey="IDEQUIPAMENTO" Type="ORDEMSERVICO" />
      <Association Name="USUARIO_EQUIPAMENTO" Member="USUARIO" ThisKey="IDUSUARIO" OtherKey="ID" Type="USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MANUTENCAOEQUIPAMENTO" Member="MANUTENCAOEQUIPAMENTO">
    <Type Name="MANUTENCAOEQUIPAMENTO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DESCRICAO" Type="System.String" DbType="VarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="IDEQUIPAMENTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="EQUIPAMENTO_MANUTENCAOEQUIPAMENTO" Member="EQUIPAMENTO" ThisKey="IDEQUIPAMENTO" OtherKey="ID" Type="EQUIPAMENTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ORDEMSERVICO" Member="ORDEMSERVICO">
    <Type Name="ORDEMSERVICO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDEQUIPAMENTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEFEITOREPASSADOPELOCLIENTE" Type="System.String" DbType="VarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="DEFEITOAPRESENTADO" Type="System.String" DbType="VarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="AVARIA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ORDEMSERVICO_ORDEMSERVICOANEXO" Member="ORDEMSERVICOANEXO" ThisKey="ID" OtherKey="IDORDEMSERVICO" Type="ORDEMSERVICOANEXO" />
      <Association Name="EQUIPAMENTO_ORDEMSERVICO" Member="EQUIPAMENTO" ThisKey="IDEQUIPAMENTO" OtherKey="ID" Type="EQUIPAMENTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ORDEMSERVICOANEXO" Member="ORDEMSERVICOANEXO">
    <Type Name="ORDEMSERVICOANEXO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ARQUIVO" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
      <Column Name="IDORDEMSERVICO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ORDEMSERVICO_ORDEMSERVICOANEXO" Member="ORDEMSERVICO" ThisKey="IDORDEMSERVICO" OtherKey="ID" Type="ORDEMSERVICO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FILIAL" Member="FILIAL">
    <Type Name="FILIAL">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMEFANTASIA" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="RAZAOSOCIAL" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CNPJ" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ENDERECO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="BAIRRO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CIDADE" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TELEFONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TELEFONE2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IDEMPRESA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FILIAL_LOCALESTOQUE" Member="LOCALESTOQUE" ThisKey="ID" OtherKey="IDFILIAL" Type="LOCALESTOQUE" />
      <Association Name="EMPRESA_FILIAL" Member="EMPRESA" ThisKey="IDEMPRESA" OtherKey="ID" Type="EMPRESA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOCALESTOQUE" Member="LOCALESTOQUE">
    <Type Name="LOCALESTOQUE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDFILIAL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LOCALESTOQUE_PRODUTOLOCALESTOQUE" Member="PRODUTOLOCALESTOQUE" ThisKey="ID" OtherKey="IDLOCALESTOQUE" Type="PRODUTOLOCALESTOQUE" />
      <Association Name="LOCALESTOQUE_VENDA" Member="VENDA" ThisKey="ID" OtherKey="IDLOCALESTOQUE" Type="VENDA" />
      <Association Name="LOCALESTOQUE_FORMAPAGAMENTO" Member="FORMAPAGAMENTO" ThisKey="ID" OtherKey="IDLOCALESTOQUE" Type="FORMAPAGAMENTO" />
      <Association Name="FILIAL_LOCALESTOQUE" Member="FILIAL" ThisKey="IDFILIAL" OtherKey="ID" Type="FILIAL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUTOLOCALESTOQUE" Member="PRODUTOLOCALESTOQUE">
    <Type Name="PRODUTOLOCALESTOQUE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPRODUTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDLOCALESTOQUE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VALORCUSTO" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="VALORVENDA" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTIDADE" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="PRODUTOLOCALESTOQUE_ITENSVENDA" Member="ITENSVENDA" ThisKey="ID" OtherKey="IDPRODUTOLOCALESTOQUE" Type="ITENSVENDA" />
      <Association Name="LOCALESTOQUE_PRODUTOLOCALESTOQUE" Member="LOCALESTOQUE" ThisKey="IDLOCALESTOQUE" OtherKey="ID" Type="LOCALESTOQUE" IsForeignKey="true" />
      <Association Name="PRODUTO_PRODUTOLOCALESTOQUE" Member="PRODUTO" ThisKey="IDPRODUTO" OtherKey="ID" Type="PRODUTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUTO" Member="PRODUTO">
    <Type Name="PRODUTO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CODIGO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="PRODUTO_PRODUTOLOCALESTOQUE" Member="PRODUTOLOCALESTOQUE" ThisKey="ID" OtherKey="IDPRODUTO" Type="PRODUTOLOCALESTOQUE" />
    </Type>
  </Table>
  <Table Name="dbo.ITENSVENDA" Member="ITENSVENDA">
    <Type Name="ITENSVENDA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CODIGO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDPRODUTOLOCALESTOQUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTIDADE" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="VALOR" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRICAO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IDLOCALESTOQUE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PRODUTOLOCALESTOQUE_ITENSVENDA" Member="PRODUTOLOCALESTOQUE" ThisKey="IDPRODUTOLOCALESTOQUE" OtherKey="ID" Type="PRODUTOLOCALESTOQUE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VENDA" Member="VENDA">
    <Type Name="VENDA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CODIGO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VALORTOTALITENS" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="VALORTOTAL" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TIPOVENDA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDLOCALESTOQUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOCALESTOQUE_VENDA" Member="LOCALESTOQUE" ThisKey="IDLOCALESTOQUE" OtherKey="ID" Type="LOCALESTOQUE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FORMAPAGAMENTO" Member="FORMAPAGAMENTO">
    <Type Name="FORMAPAGAMENTO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MODIFICADOEM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CRIADOPOR" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CRIADOEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFICADOPOR" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CODIGO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VALORFORMAPAGAMENTO" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="VALORDESCONTO" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="NSU" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CODAUTORIZACAO" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MEIOFORMAPAGAMENTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DESCRICAO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="QUANTIDADEPARCELAS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VALORACRESCIMO" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IDLOCALESTOQUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOCALESTOQUE_FORMAPAGAMENTO" Member="LOCALESTOQUE" ThisKey="IDLOCALESTOQUE" OtherKey="ID" Type="LOCALESTOQUE" IsForeignKey="true" />
    </Type>
  </Table>
</Database>